# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\addnewaccForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddNewAccoutWindow(object):
    def setupUi(self, AddNewAccoutWindow):
        AddNewAccoutWindow.setObjectName("AddNewAccoutWindow")
        AddNewAccoutWindow.resize(872, 520)
        AddNewAccoutWindow.setMinimumSize(QtCore.QSize(872, 520))
        AddNewAccoutWindow.setMaximumSize(QtCore.QSize(872, 520))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Resources/icons/add-user.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AddNewAccoutWindow.setWindowIcon(icon)
        AddNewAccoutWindow.setAutoFillBackground(False)
        AddNewAccoutWindow.setStyleSheet("QWidget\n"
"{\n"
"    background-color: #00111d;\n"
"    color: #000000;\n"
"    border-color: #000000;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLabel-----*/\n"
"QLabel\n"
"{\n"
"    background-color: #00111d;\n"
"    color: #717e87;\n"
"    border-color: #000000;\n"
"\n"
"}")
        self.centralwidget = QtWidgets.QWidget(AddNewAccoutWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 3, 851, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addaccLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana Pro Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.addaccLabel.setFont(font)
        self.addaccLabel.setStyleSheet("QLabel\n"
"{\n"
"    background-color: #00111d;\n"
"    color: #ff1066;\n"
"    border-color: #000000;\n"
"\n"
"}")
        self.addaccLabel.setScaledContents(True)
        self.addaccLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.addaccLabel.setWordWrap(False)
        self.addaccLabel.setObjectName("addaccLabel")
        self.horizontalLayout.addWidget(self.addaccLabel)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(9, 40, 124, 371))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(5, 0, 5, 4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.platform_Label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(12)
        self.platform_Label.setFont(font)
        self.platform_Label.setStyleSheet("QLabel\n"
"{\n"
"    background-color: #00111d;\n"
"    color: #ff1066;\n"
"    border-color: #000000;\n"
"\n"
"}")
        self.platform_Label.setObjectName("platform_Label")
        self.verticalLayout.addWidget(self.platform_Label)
        self.username_Label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(12)
        self.username_Label.setFont(font)
        self.username_Label.setStyleSheet("QLabel\n"
"{\n"
"    background-color: #00111d;\n"
"    color: #ff1066;\n"
"    border-color: #000000;\n"
"\n"
"}")
        self.username_Label.setObjectName("username_Label")
        self.verticalLayout.addWidget(self.username_Label)
        self.usermail_Label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(12)
        self.usermail_Label.setFont(font)
        self.usermail_Label.setStyleSheet("QLabel\n"
"{\n"
"    background-color: #00111d;\n"
"    color: #ff1066;\n"
"    border-color: #000000;\n"
"\n"
"}")
        self.usermail_Label.setObjectName("usermail_Label")
        self.verticalLayout.addWidget(self.usermail_Label)
        self.userpassword_Label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(12)
        self.userpassword_Label.setFont(font)
        self.userpassword_Label.setStyleSheet("QLabel\n"
"{\n"
"    background-color: #00111d;\n"
"    color: #ff1066;\n"
"    border-color: #000000;\n"
"\n"
"}")
        self.userpassword_Label.setObjectName("userpassword_Label")
        self.verticalLayout.addWidget(self.userpassword_Label)
        self.creationdate_Label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(12)
        self.creationdate_Label.setFont(font)
        self.creationdate_Label.setStyleSheet("QLabel\n"
"{\n"
"    background-color: #00111d;\n"
"    color: #ff1066;\n"
"    border-color: #000000;\n"
"\n"
"}")
        self.creationdate_Label.setObjectName("creationdate_Label")
        self.verticalLayout.addWidget(self.creationdate_Label)
        self.recoverycodes_Label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(12)
        self.recoverycodes_Label.setFont(font)
        self.recoverycodes_Label.setStyleSheet("QLabel\n"
"{\n"
"    background-color: #00111d;\n"
"    color: #ff1066;\n"
"    border-color: #000000;\n"
"\n"
"}")
        self.recoverycodes_Label.setObjectName("recoverycodes_Label")
        self.verticalLayout.addWidget(self.recoverycodes_Label)
        self.phonenumber_Label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(12)
        self.phonenumber_Label.setFont(font)
        self.phonenumber_Label.setStyleSheet("QLabel\n"
"{\n"
"    background-color: #00111d;\n"
"    color: #ff1066;\n"
"    border-color: #000000;\n"
"\n"
"}")
        self.phonenumber_Label.setObjectName("phonenumber_Label")
        self.verticalLayout.addWidget(self.phonenumber_Label)
        self.recoverymail_Label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(12)
        self.recoverymail_Label.setFont(font)
        self.recoverymail_Label.setStyleSheet("QLabel\n"
"{\n"
"    background-color: #00111d;\n"
"    color: #ff1066;\n"
"    border-color: #000000;\n"
"\n"
"}")
        self.recoverymail_Label.setObjectName("recoverymail_Label")
        self.verticalLayout.addWidget(self.recoverymail_Label)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(776, 40, 87, 370))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(5, 3, 5, 3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.clearPlatform_button = QtWidgets.QPushButton(self.layoutWidget2)
        self.clearPlatform_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #3de6af;\n"
"    color: #000000;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #3dffaf;\n"
"    color: #000000;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #3dc8af;\n"
"    color: #000000;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\Resources/icons/clear.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearPlatform_button.setIcon(icon1)
        self.clearPlatform_button.setObjectName("clearPlatform_button")
        self.verticalLayout_2.addWidget(self.clearPlatform_button)
        self.clearUsername_button = QtWidgets.QPushButton(self.layoutWidget2)
        self.clearUsername_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #3de6af;\n"
"    color: #000000;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #3dffaf;\n"
"    color: #000000;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #3dc8af;\n"
"    color: #000000;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}")
        self.clearUsername_button.setIcon(icon1)
        self.clearUsername_button.setObjectName("clearUsername_button")
        self.verticalLayout_2.addWidget(self.clearUsername_button)
        self.clearMail_button = QtWidgets.QPushButton(self.layoutWidget2)
        self.clearMail_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #3de6af;\n"
"    color: #000000;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #3dffaf;\n"
"    color: #000000;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #3dc8af;\n"
"    color: #000000;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}")
        self.clearMail_button.setIcon(icon1)
        self.clearMail_button.setObjectName("clearMail_button")
        self.verticalLayout_2.addWidget(self.clearMail_button)
        self.clearPassword_button = QtWidgets.QPushButton(self.layoutWidget2)
        self.clearPassword_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #3de6af;\n"
"    color: #000000;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #3dffaf;\n"
"    color: #000000;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #3dc8af;\n"
"    color: #000000;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}")
        self.clearPassword_button.setIcon(icon1)
        self.clearPassword_button.setObjectName("clearPassword_button")
        self.verticalLayout_2.addWidget(self.clearPassword_button)
        self.clearCreationDate_button = QtWidgets.QPushButton(self.layoutWidget2)
        self.clearCreationDate_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #3de6af;\n"
"    color: #000000;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #3dffaf;\n"
"    color: #000000;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #3dc8af;\n"
"    color: #000000;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}")
        self.clearCreationDate_button.setIcon(icon1)
        self.clearCreationDate_button.setObjectName("clearCreationDate_button")
        self.verticalLayout_2.addWidget(self.clearCreationDate_button)
        self.clearRecoveryCodes_button = QtWidgets.QPushButton(self.layoutWidget2)
        self.clearRecoveryCodes_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #3de6af;\n"
"    color: #000000;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #3dffaf;\n"
"    color: #000000;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #3dc8af;\n"
"    color: #000000;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}")
        self.clearRecoveryCodes_button.setIcon(icon1)
        self.clearRecoveryCodes_button.setObjectName("clearRecoveryCodes_button")
        self.verticalLayout_2.addWidget(self.clearRecoveryCodes_button)
        self.clearPhone_button = QtWidgets.QPushButton(self.layoutWidget2)
        self.clearPhone_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #3de6af;\n"
"    color: #000000;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #3dffaf;\n"
"    color: #000000;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #3dc8af;\n"
"    color: #000000;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}")
        self.clearPhone_button.setIcon(icon1)
        self.clearPhone_button.setObjectName("clearPhone_button")
        self.verticalLayout_2.addWidget(self.clearPhone_button)
        self.clearRecoveryMail_button = QtWidgets.QPushButton(self.layoutWidget2)
        self.clearRecoveryMail_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #3de6af;\n"
"    color: #000000;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #3dffaf;\n"
"    color: #000000;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #3dc8af;\n"
"    color: #000000;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}")
        self.clearRecoveryMail_button.setIcon(icon1)
        self.clearRecoveryMail_button.setObjectName("clearRecoveryMail_button")
        self.verticalLayout_2.addWidget(self.clearRecoveryMail_button)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(9, 416, 851, 84))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.save_button = QtWidgets.QPushButton(self.layoutWidget3)
        self.save_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #3de6af;\n"
"    color: #000000;\n"
"    border-color: #000000;\n"
"    padding: 10px;\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #3dffaf;\n"
"    color: #000000;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #3dc8af;\n"
"    color: #000000;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"\n"
"\n"
"\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\Resources/icons/save.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_button.setIcon(icon2)
        self.save_button.setObjectName("save_button")
        self.verticalLayout_5.addWidget(self.save_button)
        self.clearall_button = QtWidgets.QPushButton(self.layoutWidget3)
        self.clearall_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #3de6af;\n"
"    color: #000000;\n"
"    border-color: #000000;\n"
"    padding: 10px;\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #3dffaf;\n"
"    color: #000000;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #3dc8af;\n"
"    color: #000000;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"\n"
"\n"
"\n"
"}\n"
"")
        self.clearall_button.setIcon(icon1)
        self.clearall_button.setObjectName("clearall_button")
        self.verticalLayout_5.addWidget(self.clearall_button)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(140, 41, 631, 134))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.platform_lineedit = QtWidgets.QLineEdit(self.widget)
        self.platform_lineedit.setMinimumSize(QtCore.QSize(0, 40))
        self.platform_lineedit.setMaximumSize(QtCore.QSize(16777215, 40))
        self.platform_lineedit.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: #082336;\n"
"    color: #3e93ff;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #1e4b6d;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit::hover\n"
"{\n"
"    background-color: #082336;\n"
"    color: #3e93ca;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #ff1066;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit::focus\n"
"{\n"
"    \n"
"    color: #3e93ca;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #ff1066;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"")
        self.platform_lineedit.setObjectName("platform_lineedit")
        self.verticalLayout_4.addWidget(self.platform_lineedit)
        self.username_lineedit = QtWidgets.QLineEdit(self.widget)
        self.username_lineedit.setMinimumSize(QtCore.QSize(0, 40))
        self.username_lineedit.setMaximumSize(QtCore.QSize(16777215, 40))
        self.username_lineedit.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: #082336;\n"
"    color: #3e93ff;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #1e4b6d;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit::hover\n"
"{\n"
"    background-color: #082336;\n"
"    color: #3e93ca;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #ff1066;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit::focus\n"
"{\n"
"    \n"
"    color: #3e93ca;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #ff1066;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"")
        self.username_lineedit.setObjectName("username_lineedit")
        self.verticalLayout_4.addWidget(self.username_lineedit)
        self.usermail_lineedit = QtWidgets.QLineEdit(self.widget)
        self.usermail_lineedit.setMinimumSize(QtCore.QSize(0, 40))
        self.usermail_lineedit.setMaximumSize(QtCore.QSize(16777215, 40))
        self.usermail_lineedit.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: #082336;\n"
"    color: #3e93ff;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #1e4b6d;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit::hover\n"
"{\n"
"    background-color: #082336;\n"
"    color: #3e93ca;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #ff1066;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit::focus\n"
"{\n"
"    \n"
"    color: #3e93ca;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #ff1066;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"")
        self.usermail_lineedit.setObjectName("usermail_lineedit")
        self.verticalLayout_4.addWidget(self.usermail_lineedit)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(140, 181, 631, 42))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.userpassword_lineedit = QtWidgets.QLineEdit(self.widget1)
        self.userpassword_lineedit.setMinimumSize(QtCore.QSize(0, 40))
        self.userpassword_lineedit.setMaximumSize(QtCore.QSize(16777215, 40))
        self.userpassword_lineedit.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: #082336;\n"
"    color: #3e93ff;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #1e4b6d;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit::hover\n"
"{\n"
"    background-color: #082336;\n"
"    color: #3e93ca;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #ff1066;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit::focus\n"
"{\n"
"    \n"
"    color: #3e93ca;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #ff1066;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"")
        self.userpassword_lineedit.setObjectName("userpassword_lineedit")
        self.horizontalLayout_2.addWidget(self.userpassword_lineedit)
        self.randomizepass_btn = QtWidgets.QPushButton(self.widget1)
        self.randomizepass_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.randomizepass_btn.setMaximumSize(QtCore.QSize(16777215, 40))
        self.randomizepass_btn.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #ff1056;\n"
"    color: #000000;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 11px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #ff1066;\n"
"    color: #000000;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #ff1076;\n"
"    color: #000000;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\Resources/icons/randompassword.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.randomizepass_btn.setIcon(icon3)
        self.randomizepass_btn.setObjectName("randomizepass_btn")
        self.horizontalLayout_2.addWidget(self.randomizepass_btn)
        self.randompasssett_btn = QtWidgets.QPushButton(self.widget1)
        self.randompasssett_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.randompasssett_btn.setMaximumSize(QtCore.QSize(16777215, 40))
        self.randompasssett_btn.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #ff1056;\n"
"    color: #000000;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 11px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #ff1066;\n"
"    color: #000000;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #ff1076;\n"
"    color: #000000;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}")
        self.randompasssett_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(".\\Resources/icons/passett.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.randompasssett_btn.setIcon(icon4)
        self.randompasssett_btn.setObjectName("randompasssett_btn")
        self.horizontalLayout_2.addWidget(self.randompasssett_btn)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(140, 230, 631, 180))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.creationdate_lineedit = QtWidgets.QLineEdit(self.widget2)
        self.creationdate_lineedit.setMinimumSize(QtCore.QSize(0, 40))
        self.creationdate_lineedit.setMaximumSize(QtCore.QSize(16777215, 40))
        self.creationdate_lineedit.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: #082336;\n"
"    color: #3e93ff;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #1e4b6d;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit::hover\n"
"{\n"
"    background-color: #082336;\n"
"    color: #3e93ca;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #ff1066;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit::focus\n"
"{\n"
"    \n"
"    color: #3e93ca;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #ff1066;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"")
        self.creationdate_lineedit.setObjectName("creationdate_lineedit")
        self.verticalLayout_3.addWidget(self.creationdate_lineedit)
        self.recoverycodes_lineedit = QtWidgets.QLineEdit(self.widget2)
        self.recoverycodes_lineedit.setMinimumSize(QtCore.QSize(0, 40))
        self.recoverycodes_lineedit.setMaximumSize(QtCore.QSize(16777215, 40))
        self.recoverycodes_lineedit.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: #082336;\n"
"    color: #3e93ff;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #1e4b6d;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit::hover\n"
"{\n"
"    background-color: #082336;\n"
"    color: #3e93ca;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #ff1066;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit::focus\n"
"{\n"
"    \n"
"    color: #3e93ca;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #ff1066;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"")
        self.recoverycodes_lineedit.setObjectName("recoverycodes_lineedit")
        self.verticalLayout_3.addWidget(self.recoverycodes_lineedit)
        self.phonenumber_lineedit = QtWidgets.QLineEdit(self.widget2)
        self.phonenumber_lineedit.setMinimumSize(QtCore.QSize(0, 40))
        self.phonenumber_lineedit.setMaximumSize(QtCore.QSize(16777215, 40))
        self.phonenumber_lineedit.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: #082336;\n"
"    color: #3e93ff;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #1e4b6d;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit::hover\n"
"{\n"
"    background-color: #082336;\n"
"    color: #3e93ca;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #ff1066;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit::focus\n"
"{\n"
"    \n"
"    color: #3e93ca;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #ff1066;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"")
        self.phonenumber_lineedit.setObjectName("phonenumber_lineedit")
        self.verticalLayout_3.addWidget(self.phonenumber_lineedit)
        self.recoverymail_lineedit = QtWidgets.QLineEdit(self.widget2)
        self.recoverymail_lineedit.setMinimumSize(QtCore.QSize(0, 40))
        self.recoverymail_lineedit.setMaximumSize(QtCore.QSize(16777215, 40))
        self.recoverymail_lineedit.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: #082336;\n"
"    color: #3e93ff;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #1e4b6d;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit::hover\n"
"{\n"
"    background-color: #082336;\n"
"    color: #3e93ca;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #ff1066;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit::focus\n"
"{\n"
"    \n"
"    color: #3e93ca;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #ff1066;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"")
        self.recoverymail_lineedit.setObjectName("recoverymail_lineedit")
        self.verticalLayout_3.addWidget(self.recoverymail_lineedit)
        AddNewAccoutWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AddNewAccoutWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 872, 21))
        self.menubar.setObjectName("menubar")
        AddNewAccoutWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AddNewAccoutWindow)
        self.statusbar.setObjectName("statusbar")
        AddNewAccoutWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AddNewAccoutWindow)
        QtCore.QMetaObject.connectSlotsByName(AddNewAccoutWindow)

    def retranslateUi(self, AddNewAccoutWindow):
        _translate = QtCore.QCoreApplication.translate
        AddNewAccoutWindow.setWindowTitle(_translate("AddNewAccoutWindow", "Add New Account"))
        self.addaccLabel.setText(_translate("AddNewAccoutWindow", "ADD NEW ACCOUNT"))
        self.platform_Label.setText(_translate("AddNewAccoutWindow", "Platform:"))
        self.username_Label.setText(_translate("AddNewAccoutWindow", "Username:"))
        self.usermail_Label.setText(_translate("AddNewAccoutWindow", "User Mail:"))
        self.userpassword_Label.setText(_translate("AddNewAccoutWindow", "User Password:"))
        self.creationdate_Label.setText(_translate("AddNewAccoutWindow", "Creation Date:"))
        self.recoverycodes_Label.setText(_translate("AddNewAccoutWindow", "Recovery Codes:"))
        self.phonenumber_Label.setText(_translate("AddNewAccoutWindow", "Phone Number:"))
        self.recoverymail_Label.setText(_translate("AddNewAccoutWindow", "Recovery Mail:"))
        self.clearPlatform_button.setText(_translate("AddNewAccoutWindow", "Clear"))
        self.clearUsername_button.setText(_translate("AddNewAccoutWindow", "Clear"))
        self.clearMail_button.setText(_translate("AddNewAccoutWindow", "Clear"))
        self.clearPassword_button.setText(_translate("AddNewAccoutWindow", "Clear"))
        self.clearCreationDate_button.setText(_translate("AddNewAccoutWindow", "Clear"))
        self.clearRecoveryCodes_button.setText(_translate("AddNewAccoutWindow", "Clear"))
        self.clearPhone_button.setText(_translate("AddNewAccoutWindow", "Clear"))
        self.clearRecoveryMail_button.setText(_translate("AddNewAccoutWindow", "Clear"))
        self.save_button.setText(_translate("AddNewAccoutWindow", "Save Account"))
        self.clearall_button.setText(_translate("AddNewAccoutWindow", "Clear All"))
        self.randomizepass_btn.setText(_translate("AddNewAccoutWindow", "Randomize"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddNewAccoutWindow = QtWidgets.QMainWindow()
    ui = Ui_AddNewAccoutWindow()
    ui.setupUi(AddNewAccoutWindow)
    AddNewAccoutWindow.show()
    sys.exit(app.exec_())
