# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\createnewaccountForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateNewAccount(object):
    def setupUi(self, CreateNewAccount):
        CreateNewAccount.setObjectName("CreateNewAccount")
        CreateNewAccount.resize(472, 465)
        CreateNewAccount.setMinimumSize(QtCore.QSize(472, 464))
        CreateNewAccount.setMaximumSize(QtCore.QSize(472, 465))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Resources/icons/create_acc.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CreateNewAccount.setWindowIcon(icon)
        CreateNewAccount.setStyleSheet("QWidget\n"
"{\n"
"    background-color: #292f45;\n"
"    color: #000000;\n"
"    border-color: #000000;\n"
"\n"
"}")
        self.centralwidget = QtWidgets.QWidget(CreateNewAccount)
        self.centralwidget.setObjectName("centralwidget")
        self.username_crtnewacc_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.username_crtnewacc_lineedit.setGeometry(QtCore.QRect(80, 110, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana Pro Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.username_crtnewacc_lineedit.setFont(font)
        self.username_crtnewacc_lineedit.setStyleSheet("QLineEdit{\n"
"    background-color: Transparent;\n"
"    color: #b9b9bb;\n"
"    font-weight: bold;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top: 0px;\n"
"    border-left: 0px;\n"
"    border-right: 0px;\n"
"    border-color: #b9b9bb;\n"
"    padding: 10px;\n"
"\n"
"}")
        self.username_crtnewacc_lineedit.setObjectName("username_crtnewacc_lineedit")
        self.usermail_crtnewacc_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.usermail_crtnewacc_lineedit.setGeometry(QtCore.QRect(80, 180, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana Pro Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.usermail_crtnewacc_lineedit.setFont(font)
        self.usermail_crtnewacc_lineedit.setStyleSheet("QLineEdit{\n"
"    background-color: Transparent;\n"
"    color: #b9b9bb;\n"
"    font-weight: bold;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top: 0px;\n"
"    border-left: 0px;\n"
"    border-right: 0px;\n"
"    border-color: #b9b9bb;\n"
"    padding: 10px;\n"
"\n"
"}")
        self.usermail_crtnewacc_lineedit.setObjectName("usermail_crtnewacc_lineedit")
        self.password_crtnewacc_linedit = QtWidgets.QLineEdit(self.centralwidget)
        self.password_crtnewacc_linedit.setGeometry(QtCore.QRect(80, 250, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana Pro Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.password_crtnewacc_linedit.setFont(font)
        self.password_crtnewacc_linedit.setStyleSheet("QLineEdit{\n"
"    background-color: Transparent;\n"
"    color: #b9b9bb;\n"
"    font-weight: bold;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top: 0px;\n"
"    border-left: 0px;\n"
"    border-right: 0px;\n"
"    border-color: #b9b9bb;\n"
"    padding: 10px;\n"
"\n"
"}")
        self.password_crtnewacc_linedit.setObjectName("password_crtnewacc_linedit")
        self.createnewaccconfirm_btn = QtWidgets.QPushButton(self.centralwidget)
        self.createnewaccconfirm_btn.setGeometry(QtCore.QRect(94, 330, 281, 51))
        self.createnewaccconfirm_btn.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #f0742f;\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 17px;\n"
"    border-color: #f0742f;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #fc7c11;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #ff6b35;\n"
"    color: #fff;\n"
"\n"
"}")
        self.createnewaccconfirm_btn.setObjectName("createnewaccconfirm_btn")
        self.createNewAcc_label = QtWidgets.QLabel(self.centralwidget)
        self.createNewAcc_label.setGeometry(QtCore.QRect(60, 50, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana Pro Semibold")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.createNewAcc_label.setFont(font)
        self.createNewAcc_label.setStyleSheet("QLabel\n"
"{\n"
"    background-color: Transparent;\n"
"    color:#f0742f;\n"
"    border-color: #000000;\n"
"\n"
"}")
        self.createNewAcc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.createNewAcc_label.setObjectName("createNewAcc_label")
        self.saved_label = QtWidgets.QLabel(self.centralwidget)
        self.saved_label.setGeometry(QtCore.QRect(50, 380, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana Pro Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.saved_label.setFont(font)
        self.saved_label.setStyleSheet("QLabel\n"
"{\n"
"    background-color: Transparent;\n"
"    color:#f0742f;\n"
"    border-color: #000000;\n"
"\n"
"}")
        self.saved_label.setAlignment(QtCore.Qt.AlignCenter)
        self.saved_label.setObjectName("saved_label")
        CreateNewAccount.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CreateNewAccount)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 472, 21))
        self.menubar.setObjectName("menubar")
        CreateNewAccount.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CreateNewAccount)
        self.statusbar.setObjectName("statusbar")
        CreateNewAccount.setStatusBar(self.statusbar)

        self.retranslateUi(CreateNewAccount)
        QtCore.QMetaObject.connectSlotsByName(CreateNewAccount)

    def retranslateUi(self, CreateNewAccount):
        _translate = QtCore.QCoreApplication.translate
        CreateNewAccount.setWindowTitle(_translate("CreateNewAccount", "Create New Account"))
        self.username_crtnewacc_lineedit.setPlaceholderText(_translate("CreateNewAccount", "Username"))
        self.usermail_crtnewacc_lineedit.setPlaceholderText(_translate("CreateNewAccount", "Email Address"))
        self.password_crtnewacc_linedit.setPlaceholderText(_translate("CreateNewAccount", "Password"))
        self.createnewaccconfirm_btn.setText(_translate("CreateNewAccount", "Confirm and Create"))
        self.createNewAcc_label.setText(_translate("CreateNewAccount", "Create New Account"))
        self.saved_label.setText(_translate("CreateNewAccount", "Successfully Created"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateNewAccount = QtWidgets.QMainWindow()
    ui = Ui_CreateNewAccount()
    ui.setupUi(CreateNewAccount)
    CreateNewAccount.show()
    sys.exit(app.exec_())
