# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\loginForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginScreen(object):
    def setupUi(self, LoginScreen):
        LoginScreen.setObjectName("LoginScreen")
        LoginScreen.resize(445, 450)
        LoginScreen.setMinimumSize(QtCore.QSize(445, 450))
        LoginScreen.setMaximumSize(QtCore.QSize(445, 450))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Resources/icons/login.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginScreen.setWindowIcon(icon)
        LoginScreen.setStyleSheet("QWidget\n"
"{\n"
"    background-color: #292f45;\n"
"    color: #000000;\n"
"    border-color: #000000;\n"
"\n"
"}")
        LoginScreen.setInputMethodHints(QtCore.Qt.ImhNone)
        self.centralwidget = QtWidgets.QWidget(LoginScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.login_btn = QtWidgets.QPushButton(self.centralwidget)
        self.login_btn.setGeometry(QtCore.QRect(50, 230, 341, 41))
        self.login_btn.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #f0742f;\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 17px;\n"
"    border-color: #f0742f;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #fc7c11;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #ff6b35;\n"
"    color: #fff;\n"
"\n"
"}\n"
"")
        self.login_btn.setObjectName("login_btn")
        self.createnewacc_btn = QtWidgets.QPushButton(self.centralwidget)
        self.createnewacc_btn.setGeometry(QtCore.QRect(140, 280, 161, 41))
        self.createnewacc_btn.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #f0742f;\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 17px;\n"
"    border-color: #f0742f;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #fc7c11;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #ff6b35;\n"
"    color: #fff;\n"
"\n"
"}\n"
"")
        self.createnewacc_btn.setObjectName("createnewacc_btn")
        self.LoginLabel = QtWidgets.QLabel(self.centralwidget)
        self.LoginLabel.setGeometry(QtCore.QRect(40, 20, 381, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana Pro Semibold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.LoginLabel.setFont(font)
        self.LoginLabel.setStyleSheet("QLabel\n"
"{\n"
"    background-color: Transparent;\n"
"    color: #f0742f;\n"
"    border-color: #000000;\n"
"\n"
"}")
        self.LoginLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.LoginLabel.setObjectName("LoginLabel")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 80, 341, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.UserMailOrUsername_linedit = QtWidgets.QLineEdit(self.layoutWidget)
        self.UserMailOrUsername_linedit.setMinimumSize(QtCore.QSize(0, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana Pro Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.UserMailOrUsername_linedit.setFont(font)
        self.UserMailOrUsername_linedit.setWhatsThis("")
        self.UserMailOrUsername_linedit.setStyleSheet("QLineEdit{\n"
"    background-color: Transparent;\n"
"    color: #b9b9bb;\n"
"    font-weight: bold;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top: 0px;\n"
"    border-left: 0px;\n"
"    border-right: 0px;\n"
"    border-color: #b9b9bb;\n"
"    padding: 10px;\n"
"\n"
"}")
        self.UserMailOrUsername_linedit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.UserMailOrUsername_linedit.setObjectName("UserMailOrUsername_linedit")
        self.verticalLayout.addWidget(self.UserMailOrUsername_linedit)
        self.login_password_lineedit = QtWidgets.QLineEdit(self.layoutWidget)
        self.login_password_lineedit.setMinimumSize(QtCore.QSize(0, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana Pro Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.login_password_lineedit.setFont(font)
        self.login_password_lineedit.setStyleSheet("QLineEdit{\n"
"    background-color: Transparent;\n"
"    color: #b9b9bb;\n"
"    font-weight: bold;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top: 0px;\n"
"    border-left: 0px;\n"
"    border-right: 0px;\n"
"    border-color: #b9b9bb;\n"
"    padding: 10px;\n"
"\n"
"}")
        self.login_password_lineedit.setObjectName("login_password_lineedit")
        self.verticalLayout.addWidget(self.login_password_lineedit)
        self.saved_label = QtWidgets.QLabel(self.centralwidget)
        self.saved_label.setGeometry(QtCore.QRect(30, 330, 381, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana Pro Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.saved_label.setFont(font)
        self.saved_label.setStyleSheet("QLabel\n"
"{\n"
"    background-color: Transparent;\n"
"    color: #f0742f;\n"
"    border-color: #000000;\n"
"\n"
"}")
        self.saved_label.setAlignment(QtCore.Qt.AlignCenter)
        self.saved_label.setObjectName("saved_label")
        LoginScreen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginScreen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 445, 21))
        self.menubar.setObjectName("menubar")
        LoginScreen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LoginScreen)
        self.statusbar.setObjectName("statusbar")
        LoginScreen.setStatusBar(self.statusbar)

        self.retranslateUi(LoginScreen)
        QtCore.QMetaObject.connectSlotsByName(LoginScreen)

    def retranslateUi(self, LoginScreen):
        _translate = QtCore.QCoreApplication.translate
        LoginScreen.setWindowTitle(_translate("LoginScreen", "Login To Your Account"))
        self.login_btn.setText(_translate("LoginScreen", "Log In"))
        self.createnewacc_btn.setText(_translate("LoginScreen", "Create New Account"))
        self.LoginLabel.setText(_translate("LoginScreen", "Login To Your Account"))
        self.UserMailOrUsername_linedit.setPlaceholderText(_translate("LoginScreen", "Email Address Or Username"))
        self.login_password_lineedit.setPlaceholderText(_translate("LoginScreen", "Password"))
        self.saved_label.setText(_translate("LoginScreen", "Succesfully Saved"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginScreen = QtWidgets.QMainWindow()
    ui = Ui_LoginScreen()
    ui.setupUi(LoginScreen)
    LoginScreen.show()
    sys.exit(app.exec_())
