# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\PassSet.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PasswordGeneratorSettings(object):
    def setupUi(self, PasswordGeneratorSettings):
        PasswordGeneratorSettings.setObjectName("PasswordGeneratorSettings")
        PasswordGeneratorSettings.resize(368, 350)
        PasswordGeneratorSettings.setMinimumSize(QtCore.QSize(368, 350))
        PasswordGeneratorSettings.setMaximumSize(QtCore.QSize(368, 350))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Resources/icons/passett.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PasswordGeneratorSettings.setWindowIcon(icon)
        PasswordGeneratorSettings.setStyleSheet("QWidget\n"
"{\n"
"    background-color: #00111d;\n"
"    color: #000000;\n"
"    border-color: #000000;\n"
"\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(PasswordGeneratorSettings)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.passmode1_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passmode1_checkbox.sizePolicy().hasHeightForWidth())
        self.passmode1_checkbox.setSizePolicy(sizePolicy)
        self.passmode1_checkbox.setMinimumSize(QtCore.QSize(350, 0))
        self.passmode1_checkbox.setMaximumSize(QtCore.QSize(450, 16777215))
        self.passmode1_checkbox.setStyleSheet("QCheckBox\n"
"{\n"
"    background-color: transparent;\n"
"    color: #66F1FF;\n"
"    border-color: #000000;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: #00111d;\n"
"    border: 1px solid #2aaaa8;\n"
"    width: 12px;\n"
"    height: 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    background-color: #1f2b2b;\n"
"    border: 1px solid #ff1066;\n"
"    \n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:unchecked:hover\n"
"{\n"
"    border: 1px solid #ff1076;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::disabled\n"
"{\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:disabled\n"
"{\n"
"    background-color: #656565;\n"
"    color: #656565;\n"
"    border: 1px solid #656565;\n"
"\n"
"}")
        self.passmode1_checkbox.setObjectName("passmode1_checkbox")
        self.gridLayout_2.addWidget(self.passmode1_checkbox, 0, 0, 1, 1)
        self.passmode2_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.passmode2_checkbox.setStyleSheet("QCheckBox\n"
"{\n"
"    background-color: transparent;\n"
"    color: #66F1FF;\n"
"    border-color: #000000;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: #00111d;\n"
"    border: 1px solid #2aaaa8;\n"
"    width: 12px;\n"
"    height: 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    background-color: #1f2b2b;\n"
"    border: 1px solid #ff1066;\n"
"    \n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:unchecked:hover\n"
"{\n"
"    border: 1px solid #ff1076;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::disabled\n"
"{\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:disabled\n"
"{\n"
"    background-color: #656565;\n"
"    color: #656565;\n"
"    border: 1px solid #656565;\n"
"\n"
"}")
        self.passmode2_checkbox.setObjectName("passmode2_checkbox")
        self.gridLayout_2.addWidget(self.passmode2_checkbox, 1, 0, 1, 1)
        self.passmode3_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.passmode3_checkbox.setStyleSheet("QCheckBox\n"
"{\n"
"    background-color: transparent;\n"
"    color: #66F1FF;\n"
"    border-color: #000000;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: #00111d;\n"
"    border: 1px solid #2aaaa8;\n"
"    width: 12px;\n"
"    height: 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    background-color: #1f2b2b;\n"
"    border: 1px solid #ff1066;\n"
"    \n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:unchecked:hover\n"
"{\n"
"    border: 1px solid #ff1076;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::disabled\n"
"{\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:disabled\n"
"{\n"
"    background-color: #656565;\n"
"    color: #656565;\n"
"    border: 1px solid #656565;\n"
"\n"
"}")
        self.passmode3_checkbox.setObjectName("passmode3_checkbox")
        self.gridLayout_2.addWidget(self.passmode3_checkbox, 2, 0, 1, 1)
        self.passmode4_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.passmode4_checkbox.setStyleSheet("QCheckBox\n"
"{\n"
"    background-color: transparent;\n"
"    color: #66F1FF;\n"
"    border-color: #000000;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: #00111d;\n"
"    border: 1px solid #2aaaa8;\n"
"    width: 12px;\n"
"    height: 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    background-color: #1f2b2b;\n"
"    border: 1px solid #ff1066;\n"
"    \n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:unchecked:hover\n"
"{\n"
"    border: 1px solid #ff1076;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::disabled\n"
"{\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:disabled\n"
"{\n"
"    background-color: #656565;\n"
"    color: #656565;\n"
"    border: 1px solid #656565;\n"
"\n"
"}")
        self.passmode4_checkbox.setObjectName("passmode4_checkbox")
        self.gridLayout_2.addWidget(self.passmode4_checkbox, 3, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.minchar_label = QtWidgets.QLabel(self.centralwidget)
        self.minchar_label.setMaximumSize(QtCore.QSize(16777215, 10))
        self.minchar_label.setStyleSheet("QLabel\n"
"{\n"
"    background-color: #00111d;\n"
"    color: #66F1FF;\n"
"    border-color: #000000;\n"
"\n"
"}")
        self.minchar_label.setObjectName("minchar_label")
        self.gridLayout.addWidget(self.minchar_label, 0, 0, 1, 1)
        self.minchar_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.minchar_lineedit.setMinimumSize(QtCore.QSize(0, 35))
        self.minchar_lineedit.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: #082336;\n"
"    color: #ff1056;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #1e4b6d;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit::hover\n"
"{\n"
"    background-color: #082336;\n"
"    color: #ff1056;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #ff1056;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit::focus\n"
"{\n"
"    \n"
"    color: #ff1056;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #ff1066;\n"
"    padding: 10px;\n"
"\n"
"}")
        self.minchar_lineedit.setObjectName("minchar_lineedit")
        self.gridLayout.addWidget(self.minchar_lineedit, 1, 0, 1, 1)
        self.maxchar_label = QtWidgets.QLabel(self.centralwidget)
        self.maxchar_label.setMaximumSize(QtCore.QSize(16777215, 10))
        self.maxchar_label.setStyleSheet("QLabel\n"
"{\n"
"    background-color: #00111d;\n"
"    color: #66F1FF;\n"
"    border-color: #000000;\n"
"\n"
"}")
        self.maxchar_label.setObjectName("maxchar_label")
        self.gridLayout.addWidget(self.maxchar_label, 2, 0, 1, 1)
        self.maxchar_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.maxchar_lineedit.setMinimumSize(QtCore.QSize(0, 35))
        self.maxchar_lineedit.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: #082336;\n"
"    color: #ff1056;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #1e4b6d;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit::hover\n"
"{\n"
"    background-color: #082336;\n"
"    color: #ff1056;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #ff1056;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit::focus\n"
"{\n"
"    \n"
"    color: #ff1056;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #ff1066;\n"
"    padding: 10px;\n"
"\n"
"}")
        self.maxchar_lineedit.setObjectName("maxchar_lineedit")
        self.gridLayout.addWidget(self.maxchar_lineedit, 3, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 4, 0, 1, 1)
        self.save_passsett_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_passsett_btn.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #3de6af;\n"
"    color: #000000;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"    border-radius: 16px;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #3dffaf;\n"
"    color: #000000;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #3dc8af;\n"
"    color: #000000;\n"
"    border-style: 1px solid;\n"
"    border-color: #ff1066;\n"
"    font-weight : bold;\n"
"    padding: 13px;\n"
"\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\Resources/icons/save.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_passsett_btn.setIcon(icon1)
        self.save_passsett_btn.setObjectName("save_passsett_btn")
        self.gridLayout_2.addWidget(self.save_passsett_btn, 5, 0, 1, 1)
        self.saved_label = QtWidgets.QLabel(self.centralwidget)
        self.saved_label.setEnabled(True)
        self.saved_label.setMinimumSize(QtCore.QSize(0, 20))
        self.saved_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.saved_label.setStyleSheet("QLabel\n"
"{\n"
"    background-color: #00111d;\n"
"    color: #66F1FF;\n"
"    border-color: #000000;\n"
"\n"
"}")
        self.saved_label.setAlignment(QtCore.Qt.AlignCenter)
        self.saved_label.setWordWrap(False)
        self.saved_label.setObjectName("saved_label")
        self.gridLayout_2.addWidget(self.saved_label, 6, 0, 1, 1)
        PasswordGeneratorSettings.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PasswordGeneratorSettings)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 368, 21))
        self.menubar.setObjectName("menubar")
        PasswordGeneratorSettings.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PasswordGeneratorSettings)
        self.statusbar.setObjectName("statusbar")
        PasswordGeneratorSettings.setStatusBar(self.statusbar)

        self.retranslateUi(PasswordGeneratorSettings)
        QtCore.QMetaObject.connectSlotsByName(PasswordGeneratorSettings)

    def retranslateUi(self, PasswordGeneratorSettings):
        _translate = QtCore.QCoreApplication.translate
        PasswordGeneratorSettings.setWindowTitle(_translate("PasswordGeneratorSettings", "Password Generator Settings"))
        self.passmode1_checkbox.setText(_translate("PasswordGeneratorSettings", "Contains Special Chars"))
        self.passmode2_checkbox.setText(_translate("PasswordGeneratorSettings", "Contains UpperCase Letters"))
        self.passmode3_checkbox.setText(_translate("PasswordGeneratorSettings", "Contains LowerCase Letters"))
        self.passmode4_checkbox.setText(_translate("PasswordGeneratorSettings", "Contains Digits"))
        self.minchar_label.setText(_translate("PasswordGeneratorSettings", "Minimum Character Count"))
        self.maxchar_label.setText(_translate("PasswordGeneratorSettings", "Maximum Character Count"))
        self.save_passsett_btn.setText(_translate("PasswordGeneratorSettings", "Save Settings"))
        self.saved_label.setText(_translate("PasswordGeneratorSettings", "Succesfully Saved!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PasswordGeneratorSettings = QtWidgets.QMainWindow()
    ui = Ui_PasswordGeneratorSettings()
    ui.setupUi(PasswordGeneratorSettings)
    PasswordGeneratorSettings.show()
    sys.exit(app.exec_())
