# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\selectionForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(522, 778)
        MainWindow.setMaximumSize(QtCore.QSize(522, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Resources/icons/vault.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget\n"
"{\n"
"    background-color: #1a1a1a;\n"
"    color: #000000;\n"
"\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.generalLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(22)
        self.generalLabel.setFont(font)
        self.generalLabel.setStyleSheet("QLabel\n"
"{\n"
"    background-color: transparent;\n"
"    color: #ff1056;\n"
"}")
        self.generalLabel.setObjectName("generalLabel")
        self.gridLayout.addWidget(self.generalLabel, 0, 0, 1, 2)
        self.login_logout_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Verdana Pro Semibold")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.login_logout_btn.setFont(font)
        self.login_logout_btn.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #ff1056;\n"
"    color: #fff;\n"
"    font-size: 11px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #CB6FFF;\n"
"\n"
"}")
        self.login_logout_btn.setObjectName("login_logout_btn")
        self.gridLayout.addWidget(self.login_logout_btn, 1, 0, 1, 2)
        self.acc_Table = QtWidgets.QTableWidget(self.centralwidget)
        self.acc_Table.setEnabled(False)
        self.acc_Table.setMaximumSize(QtCore.QSize(501, 16777215))
        self.acc_Table.setStyleSheet("QTableWidget\n"
"{\n"
"    background-color: #450079;\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"    color: #f0f0f0;\n"
"    gridline-color: gray;\n"
"    outline : 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableWidget::disabled\n"
"{\n"
"    background-color: #242526;\n"
"    border: 1px solid #32414B;\n"
"    color: #656565;\n"
"    gridline-color: #656565;\n"
"    outline : 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableWidget::item:hover \n"
"{\n"
"    background-color: #ff1056;\n"
"    color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableWidget::item:selected \n"
"{\n"
"    background-color: #71FF3D;\n"
"    color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableWidget::item:selected:disabled\n"
"{\n"
"    background-color: #1a1b1c;\n"
"    border: 2px solid #525251;\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableCornerButton::section\n"
"{\n"
"    background-color: #ff1056;\n"
"    color: #ff1056;\n"
"    border-radius: 8px;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderWidget::section\n"
"{\n"
"    color: #ff1056;\n"
"    border-top: 0px;\n"
"    border-bottom: 1px solid gray;\n"
"    border-right: 1px solid gray;\n"
"    background-color: #ff1056;\n"
"    border-radius: 15px;\n"
"    margin-top:1px;\n"
"    margin-bottom:1px;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderWidget::section:disabled\n"
"{\n"
"    background-color: #525251;\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderWidget::section:checked\n"
"{\n"
"    color: #000;\n"
"    background-color: #ff3333;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderWidget::section:checked:disabled\n"
"{\n"
"    color: #656565;\n"
"    background-color: #525251;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderWidget::section::vertical::first,\n"
"QHeaderWidget::section::vertical::only-one\n"
"{\n"
"    border-top: 1px solid #353635;\n"
"    border-radius: 8px;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderWidget::section::vertical\n"
"{\n"
"    border-top: 1px solid #353635;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderWidget::section::horizontal::first,\n"
"QHeaderWidget::section::horizontal::only-one\n"
"{\n"
"    border-left: 1px solid #353635;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderWidget::section::horizontal\n"
"{\n"
"    border-left: 1px solid #353635;\n"
"\n"
"}")
        self.acc_Table.setObjectName("acc_Table")
        self.acc_Table.setColumnCount(3)
        self.acc_Table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.acc_Table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.acc_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.acc_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.acc_Table.setHorizontalHeaderItem(2, item)
        self.acc_Table.horizontalHeader().setVisible(True)
        self.acc_Table.horizontalHeader().setCascadingSectionResizes(False)
        self.acc_Table.horizontalHeader().setDefaultSectionSize(120)
        self.acc_Table.horizontalHeader().setMinimumSectionSize(0)
        self.gridLayout.addWidget(self.acc_Table, 2, 0, 1, 2)
        self.examineButton = QtWidgets.QPushButton(self.centralwidget)
        self.examineButton.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Verdana Pro Semibold")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.examineButton.setFont(font)
        self.examineButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #ff1056;\n"
"    color: #fff;\n"
"    font-size: 11px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #CB6FFF;\n"
"\n"
"}")
        self.examineButton.setObjectName("examineButton")
        self.gridLayout.addWidget(self.examineButton, 3, 0, 1, 1)
        self.addnewButton = QtWidgets.QPushButton(self.centralwidget)
        self.addnewButton.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Verdana Pro Cond")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.addnewButton.setFont(font)
        self.addnewButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #ff1056;\n"
"    color: #fff;\n"
"    font-size: 11px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #CB6FFF;\n"
"\n"
"}")
        self.addnewButton.setObjectName("addnewButton")
        self.gridLayout.addWidget(self.addnewButton, 3, 1, 1, 1)
        self.lockTheAccs_btn = QtWidgets.QPushButton(self.centralwidget)
        self.lockTheAccs_btn.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Verdana Pro Cond")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lockTheAccs_btn.setFont(font)
        self.lockTheAccs_btn.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #ff1056;\n"
"    color: #fff;\n"
"    font-size: 11px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #CB6FFF;\n"
"\n"
"}")
        self.lockTheAccs_btn.setObjectName("lockTheAccs_btn")
        self.gridLayout.addWidget(self.lockTheAccs_btn, 4, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 522, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Account Storage"))
        self.generalLabel.setText(_translate("MainWindow", "All Stored Accounts Are Down Below."))
        self.login_logout_btn.setText(_translate("MainWindow", "Login to Access Your Accounts"))
        self.acc_Table.setSortingEnabled(True)
        item = self.acc_Table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.acc_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Platform"))
        item = self.acc_Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Username"))
        item = self.acc_Table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "User Mail"))
        self.examineButton.setText(_translate("MainWindow", "Examine the selected account."))
        self.addnewButton.setText(_translate("MainWindow", "Add New"))
        self.lockTheAccs_btn.setText(_translate("MainWindow", "Safe Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
