# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selectionForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(522, 495)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.examineButton = QtWidgets.QPushButton(self.centralwidget)
        self.examineButton.setGeometry(QtCore.QRect(120, 380, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana Pro Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.examineButton.setFont(font)
        self.examineButton.setObjectName("examineButton")
        self.addnewButton = QtWidgets.QPushButton(self.centralwidget)
        self.addnewButton.setGeometry(QtCore.QRect(310, 380, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana Pro Cond")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.addnewButton.setFont(font)
        self.addnewButton.setObjectName("addnewButton")
        self.generalLabel = QtWidgets.QLabel(self.centralwidget)
        self.generalLabel.setGeometry(QtCore.QRect(10, 20, 511, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(22)
        self.generalLabel.setFont(font)
        self.generalLabel.setObjectName("generalLabel")
        self.acc_Table = QtWidgets.QTableWidget(self.centralwidget)
        self.acc_Table.setGeometry(QtCore.QRect(10, 80, 501, 291))
        self.acc_Table.setObjectName("acc_Table")
        self.acc_Table.setColumnCount(3)
        self.acc_Table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.acc_Table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.acc_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.acc_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.acc_Table.setHorizontalHeaderItem(2, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 522, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.examineButton.setText(_translate("MainWindow", "Examine the selected account."))
        self.addnewButton.setText(_translate("MainWindow", "Add New"))
        self.generalLabel.setText(_translate("MainWindow", "All Stored Accounts Are Down Below."))
        item = self.acc_Table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.acc_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Platform"))
        item = self.acc_Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Username"))
        item = self.acc_Table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "User Mail"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
